name: Deployment on Main Branch

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.0
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="vars.tfvars" -no-color

      - name: Terraform Apply
        run: terraform apply -var-file="vars.tfvars" -auto-approve
